"""notes-db-2025-10-28-10-31-17

Revision ID: 176a0512e7b2
Revises: 8635c6687147
Create Date: 2025-10-28 10:31:18.104751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '176a0512e7b2'
down_revision: Union[str, None] = '8635c6687147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('note_cd_id', sa.Integer(), nullable=False),
    sa.Column('note_tx_title', sa.String(length=150), nullable=False),
    sa.Column('note_tx_description', sa.Text(), nullable=False),
    sa.Column('note_dt_created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('note_cd_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    # ### end Alembic commands ###
